version: "2"
services:
  data:
    image: python:3.6
    volumes:
      - ./:/app
      - ./data:/data

  # shares volume with other images so we can use COPY
  db:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=census
      - POSTGRES_PASSWORD=census
    volumes_from:
      - data

  app:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - PGHOST=db
      - POSTGRES_USER=census
      - POSTGRES_PASSWORD=census
    ports:
      - "80:8081"
    volumes:
      - ./web:/app
    depends_on:
      - "db"
